/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";
import vancouverScene from '../assets/3d/Vancouver.glb'
import { a } from "@react-spring/three"

const Vancouver = ({isRotating, setIsRotating, ...props}) => {
  const vancouverRef = useRef();

  const { gl, viewport } = useThree();

  const { nodes, materials } = useGLTF(vancouverScene);

  const lastX = useRef(0);
  const rotationSpeed = useRef(0);
  const dampingFactor = 0.95;

  const handlePointerDown = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(true);

    const clientX = event.touches ? event.touches[0].clientX : event.clientX
    lastX.current = clientX;
  }

  const handlePointerUp = (e) => {
    e.stopPropagation();
    e.preventDefault();
    setIsRotating(false);
  }

  const handlePointerMove = (e) => {
    e.stopPropagation();
    e.preventDefault();
    //setIsRotating(true);

    if(isRotating){
      const clientX = e.touches ? e.touches[0].clientX : e.clientX

      const delta = (clientX - lastX.current) / viewport.width;

      vancouverRef.current.rotation.y += delta * 0.01 * Math.PI;

      lastX.current - clientX;

      rotationSpeed.current - delta * 0.01 * Math.PI;

    }
  }

  const handleKeyDown = (e) => {
    if(e.key === 'ArrowLeft') {
      if(!isRotating) {
        setIsRotating(true);
        vancouverRef.current.rotation.y += 0.01 * Math.PI;
      }
    }else{
      if(e.key === 'ArrowRight'){
        if(!isRotating){
          setIsRotating(true);
          vancouverRef.current.rotation.y -= 0.01 * Math.PI;
          console.log("Right arrow key pressed!"); // Added console log
        }
      }
    }
  }

  const handleKeyUp = (e) => {
    if(e.key === 'ArrowLeft' || e.key === 'ArrowRight'){
      setIsRotating(false);
    }
  }

  useFrame(() => {
    if(!isRotating) {
      rotationSpeed.current *= dampingFactor;

      if(Math.abs(rotationSpeed.current) < 0.001){
        rotationSpeed.current = 0;
      }

      vancouverRef.current.rotation.y += rotationSpeed.current;

    } else {
      const rotation = vancouverRef.current.rotation.y;

      const normalizedRotation =
        ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

      // Set the current stage based on the city orientation
      switch (true) {
        case normalizedRotation >= 5.45 && normalizedRotation <= 5.85:
          setCurrentStage(4);
          break;
        case normalizedRotation >= 0.85 && normalizedRotation <= 1.3:
          setCurrentStage(3);
          break;
        case normalizedRotation >= 2.4 && normalizedRotation <= 2.6:
          setCurrentStage(2);
          break;
        case normalizedRotation >= 4.25 && normalizedRotation <= 4.75:
          setCurrentStage(1);
          break;
        default:
          setCurrentStage(null);
      }
    }
  })

  

  useEffect(() => {
    const canvas = gl.domElement;
    canvas.addEventListener('pointerdown', handlePointerDown);
    canvas.addEventListener('pointerup', handlePointerUp);
    canvas.addEventListener('pointermove', handlePointerMove)
    document.addEventListener('keydown', handleKeyDown);
    document.addEventListener('keyup', handleKeyUp)

    return () => {
      canvas.removeEventListener('pointerdown', handlePointerDown);
      canvas.removeEventListener('pointerup', handlePointerUp);
      canvas.removeEventListener('pointermove', handlePointerMove);
      document.removeEventListener('keydown', handleKeyDown);
      document.removeEventListener('keyup', handleKeyUp)
    }

  }, [gl, handlePointerDown, handlePointerUp, handlePointerMove])

  return (
    <a.group ref={vancouverRef}{...props} >
      <mesh
        
        
        geometry={nodes.group1452617283.geometry}
        material={materials.mat10}
      />
      <mesh
        
        
        geometry={nodes.group1926126815.geometry}
        material={materials.mat5}
      />
      <mesh
        
        
        geometry={nodes.group269306622.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.group62122215.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.group462179313.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.group32002972.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.group1859955707.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.group1600036614.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.group758244815.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.group1297686250.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.group81821235.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.group840029287.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.group644830360.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.group264317860.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.group740519829.geometry}
        material={materials.mat11}
      />
      <mesh
        
        
        geometry={nodes.group1921196339.geometry}
        material={materials.mat11}
      />
      <mesh
        
        
        geometry={nodes.group960292067.geometry}
        material={materials.mat11}
      />
      <mesh
        
        
        geometry={nodes.group664967870.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.group693226123.geometry}
        material={materials.mat17}
      />
      <mesh
        
        
        geometry={nodes.group394304578.geometry}
        material={materials.mat17}
      />
      <mesh
        
        
        geometry={nodes.group2072235421.geometry}
        material={materials.mat17}
      />
      <mesh
        
        
        geometry={nodes.group381120477.geometry}
        material={materials.mat17}
      />
      <mesh
        
        
        geometry={nodes.group305972276.geometry}
        material={materials.mat17}
      />
      <mesh
        
        
        geometry={nodes.group411193827.geometry}
        material={materials.mat17}
      />
      <mesh
        
        
        geometry={nodes.group678392605.geometry}
        material={materials.mat11}
      />
      <mesh
        
        
        geometry={nodes.group1331905068.geometry}
        material={materials.mat11}
      />
      <mesh
        
        
        geometry={nodes.group228739432.geometry}
        material={materials.mat11}
      />
      <mesh
        
        
        geometry={nodes.group61007489.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.group2146409170.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.group49840277.geometry}
        material={materials.mat11}
      />
      <mesh
        
        
        geometry={nodes.group106678485.geometry}
        material={materials.mat11}
      />
      <mesh
        
        
        geometry={nodes.group886253053.geometry}
        material={materials.mat11}
      />
      <mesh
        
        
        geometry={nodes.group1628733608.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.group1092607654.geometry}
        material={materials.mat17}
      />
      <mesh
        
        
        geometry={nodes.group91675880.geometry}
        material={materials.mat17}
      />
      <mesh
        
        
        geometry={nodes.group1582874580.geometry}
        material={materials.mat17}
      />
      <mesh
        
        
        geometry={nodes.group1111343245.geometry}
        material={materials.mat17}
      />
      <mesh
        
        
        geometry={nodes.group1502999131.geometry}
        material={materials.mat10}
      />
      <mesh
        
        
        geometry={nodes.group1247129074.geometry}
        material={materials.mat10}
      />
      <mesh
        
        
        geometry={nodes.group1599426184.geometry}
        material={materials.mat10}
      />
      <mesh
        
        
        geometry={nodes.group980904771.geometry}
        material={materials.mat10}
      />
      <mesh
        
        
        geometry={nodes.group1595824761.geometry}
        material={materials.mat10}
      />
      <mesh
        
        
        geometry={nodes.group750603090.geometry}
        material={materials.mat10}
      />
      <mesh
        
        
        geometry={nodes.group592803558.geometry}
        material={materials.mat5}
      />
      <mesh
        
        
        geometry={nodes.group1492146600.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.group86307362.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.group390084612.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.group591182058.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.group371943742.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.group1190091320.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.group863499552.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.group1419798842.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.group1719381167.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.group607067024.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.group1721228000.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.group282759822.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.group1602713423.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.group465555899.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.group1550195885.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.group197357736.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.group1334676454.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.group1802490509.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.group970021958.geometry}
        material={materials.mat11}
      />
      <mesh
        
        
        geometry={nodes.group1688249756.geometry}
        material={materials.mat11}
      />
      <mesh
        
        
        geometry={nodes.group1622299973.geometry}
        material={materials.mat11}
      />
      <mesh
        
        
        geometry={nodes.group1350700828.geometry}
        material={materials.mat11}
      />
      <mesh
        
        
        geometry={nodes.group751619568.geometry}
        material={materials.mat11}
      />
      <mesh
        
        
        geometry={nodes.group2019320654.geometry}
        material={materials.mat11}
      />
      <mesh
        
        
        geometry={nodes.group220399284.geometry}
        material={materials.mat11}
      />
      <mesh
        
        
        geometry={nodes.group1407108972.geometry}
        material={materials.mat11}
      />
      <mesh
        
        
        geometry={nodes.group1198249082.geometry}
        material={materials.mat11}
      />
      <mesh
        
        
        geometry={nodes.group160437510.geometry}
        material={materials.mat11}
      />
      <mesh
        
        
        geometry={nodes.group1205835326.geometry}
        material={materials.mat11}
      />
      <mesh
        
        
        geometry={nodes.mesh1656777012.geometry}
        material={materials.mat10}
      />
      <mesh
        
        
        geometry={nodes.mesh1656777012_1.geometry}
        material={materials.mat22}
      />
      <mesh
        
        
        geometry={nodes.mesh1971097135.geometry}
        material={materials.mat11}
      />
      <mesh
        
        
        geometry={nodes.mesh1971097135_1.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh944212785.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.mesh944212785_1.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh441989801.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh441989801_1.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.mesh1533200203.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh1533200203_1.geometry}
        material={materials.mat5}
      />
      <mesh
        
        
        geometry={nodes.mesh2085297235.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh2085297235_1.geometry}
        material={materials.mat5}
      />
      <mesh
        
        
        geometry={nodes.mesh634886533.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh634886533_1.geometry}
        material={materials.mat5}
      />
      <mesh
        
        
        geometry={nodes.mesh1023818653.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh1023818653_1.geometry}
        material={materials.mat5}
      />
      <mesh
        
        
        geometry={nodes.mesh1895269739.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh1895269739_1.geometry}
        material={materials.mat5}
      />
      <mesh
        
        
        geometry={nodes.mesh486381022.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh486381022_1.geometry}
        material={materials.mat5}
      />
      <mesh
        
        
        geometry={nodes.mesh13433428.geometry}
        material={materials.mat5}
      />
      <mesh
        
        
        geometry={nodes.mesh13433428_1.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh747770077.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh747770077_1.geometry}
        material={materials.mat5}
      />
      <mesh
        
        
        geometry={nodes.mesh1755377577.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh1755377577_1.geometry}
        material={materials.mat5}
      />
      <mesh
        
        
        geometry={nodes.mesh1148249337.geometry}
        material={materials.mat15}
      />
      <mesh
        
        
        geometry={nodes.mesh1148249337_1.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.mesh1914318900.geometry}
        material={materials.mat3}
      />
      <mesh
        
        
        geometry={nodes.mesh1914318900_1.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh1589297463.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh1589297463_1.geometry}
        material={materials.mat3}
      />
      <mesh
        
        
        geometry={nodes.mesh149046089.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh149046089_1.geometry}
        material={materials.mat5}
      />
      <mesh
        
        
        geometry={nodes.mesh209975484.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh209975484_1.geometry}
        material={materials.mat12}
      />
      <mesh
        
        
        geometry={nodes.mesh1367155909.geometry}
        material={materials.mat18}
      />
      <mesh
        
        
        geometry={nodes.mesh1367155909_1.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh368050660.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh368050660_1.geometry}
        material={materials.mat19}
      />
      <mesh
        
        
        geometry={nodes.mesh308963709.geometry}
        material={materials.mat10}
      />
      <mesh
        
        
        geometry={nodes.mesh308963709_1.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh500483907.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh500483907_1.geometry}
        material={materials.mat9}
      />
      <mesh
        
        
        geometry={nodes.mesh748734138.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh748734138_1.geometry}
        material={materials.mat18}
      />
      <mesh
        
        
        geometry={nodes.mesh57321760.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh57321760_1.geometry}
        material={materials.mat9}
      />
      <mesh
        
        
        geometry={nodes.mesh1978860707.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh1978860707_1.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.mesh270291541.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh270291541_1.geometry}
        material={materials.mat10}
      />
      <mesh
        
        
        geometry={nodes.mesh1236667903.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh1236667903_1.geometry}
        material={materials.mat4}
      />
      <mesh
        
        
        geometry={nodes.mesh984249092.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh984249092_1.geometry}
        material={materials.mat16}
      />
      <mesh
        
        
        geometry={nodes.mesh713317902.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh713317902_1.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.mesh592530000.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh592530000_1.geometry}
        material={materials.mat3}
      />
      <mesh
        
        
        geometry={nodes.mesh592530000_2.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.mesh308072958.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh308072958_1.geometry}
        material={materials.mat16}
      />
      <mesh
        
        
        geometry={nodes.mesh1735703239.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh1735703239_1.geometry}
        material={materials.mat16}
      />
      <mesh
        
        
        geometry={nodes.mesh721168951.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh721168951_1.geometry}
        material={materials.mat13}
      />
      <mesh
        
        
        geometry={nodes.mesh608434854.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh608434854_1.geometry}
        material={materials.mat13}
      />
      <mesh
        
        
        geometry={nodes.mesh1862259937.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh1862259937_1.geometry}
        material={materials.mat13}
      />
      <mesh
        
        
        geometry={nodes.mesh334606726.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh334606726_1.geometry}
        material={materials.mat19}
      />
      <mesh
        
        
        geometry={nodes.mesh1161448215.geometry}
        material={materials.mat19}
      />
      <mesh
        
        
        geometry={nodes.mesh1161448215_1.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh380869932.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.mesh380869932_1.geometry}
        material={materials.mat22}
      />
      <mesh
        
        
        geometry={nodes.mesh43143167.geometry}
        material={materials.mat4}
      />
      <mesh
        
        
        geometry={nodes.mesh43143167_1.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.mesh43143167_2.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh1742195230.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh1742195230_1.geometry}
        material={materials.mat4}
      />
      <mesh
        
        
        geometry={nodes.mesh1742195230_2.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.mesh1228860991.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh1228860991_1.geometry}
        material={materials.mat4}
      />
      <mesh
        
        
        geometry={nodes.mesh1228860991_2.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.mesh672612964.geometry}
        material={materials.mat12}
      />
      <mesh
        
        
        geometry={nodes.mesh672612964_1.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh1609886918.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh1609886918_1.geometry}
        material={materials.mat18}
      />
      <mesh
        
        
        geometry={nodes.mesh1385259583.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh1385259583_1.geometry}
        material={materials.mat5}
      />
      <mesh
        
        
        geometry={nodes.mesh482221332.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh482221332_1.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.mesh1391462193.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh1391462193_1.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.mesh1703659211.geometry}
        material={materials.mat18}
      />
      <mesh
        
        
        geometry={nodes.mesh1703659211_1.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh1563168281.geometry}
        material={materials.mat5}
      />
      <mesh
        
        
        geometry={nodes.mesh1563168281_1.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh1563168281_2.geometry}
        material={materials.mat4}
      />
      <mesh
        
        
        geometry={nodes.mesh610326153.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.mesh610326153_1.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh1379738823.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh1379738823_1.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.mesh2121202750.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh2121202750_1.geometry}
        material={materials.mat5}
      />
      <mesh
        
        
        geometry={nodes.mesh2121202750_2.geometry}
        material={materials.mat4}
      />
      <mesh
        
        
        geometry={nodes.mesh1659243643.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.mesh1659243643_1.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh1115883482.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh1115883482_1.geometry}
        material={materials.mat3}
      />
      <mesh
        
        
        geometry={nodes.mesh1115883482_2.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.mesh2054733290.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh2054733290_1.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.mesh1949868650.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.mesh1949868650_1.geometry}
        material={materials.mat22}
      />
      <mesh
        
        
        geometry={nodes.mesh1518361734.geometry}
        material={materials.mat22}
      />
      <mesh
        
        
        geometry={nodes.mesh1518361734_1.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.mesh976429815.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.mesh976429815_1.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh2001573440.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh2001573440_1.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.mesh751163001.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh751163001_1.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.mesh1786607626.geometry}
        material={materials.mat15}
      />
      <mesh
        
        
        geometry={nodes.mesh1786607626_1.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.mesh1786607626_2.geometry}
        material={materials.mat16}
      />
      <mesh
        
        
        geometry={nodes.mesh622440097.geometry}
        material={materials.mat4}
      />
      <mesh
        
        
        geometry={nodes.mesh622440097_1.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh626518297.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh626518297_1.geometry}
        material={materials.mat4}
      />
      <mesh
        
        
        geometry={nodes.mesh93306127.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh93306127_1.geometry}
        material={materials.mat5}
      />
      <mesh
        
        
        geometry={nodes.mesh1100157397.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh1100157397_1.geometry}
        material={materials.mat5}
      />
      <mesh
        
        
        geometry={nodes.mesh502536234.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh502536234_1.geometry}
        material={materials.mat5}
      />
      <mesh
        
        
        geometry={nodes.mesh523920511.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh523920511_1.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.mesh1831822204.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh1831822204_1.geometry}
        material={materials.mat5}
      />
      <mesh
        
        
        geometry={nodes.mesh299204456.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh299204456_1.geometry}
        material={materials.mat5}
      />
      <mesh
        
        
        geometry={nodes.mesh86763974.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh86763974_1.geometry}
        material={materials.mat5}
      />
      <mesh
        
        
        geometry={nodes.mesh61455779.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh61455779_1.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.mesh1344587834.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh1344587834_1.geometry}
        material={materials.mat4}
      />
      <mesh
        
        
        geometry={nodes.mesh1460322968.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh1460322968_1.geometry}
        material={materials.mat4}
      />
      <mesh
        
        
        geometry={nodes.mesh793771576.geometry}
        material={materials.mat10}
      />
      <mesh
        
        
        geometry={nodes.mesh793771576_1.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh1846468049.geometry}
        material={materials.mat10}
      />
      <mesh
        
        
        geometry={nodes.mesh1846468049_1.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh643711727.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh643711727_1.geometry}
        material={materials.mat10}
      />
      <mesh
        
        
        geometry={nodes.mesh2084601409.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh2084601409_1.geometry}
        material={materials.mat4}
      />
      <mesh
        
        
        geometry={nodes.mesh1431825437.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh1431825437_1.geometry}
        material={materials.mat20}
      />
      <mesh
        
        
        geometry={nodes.mesh1431825437_2.geometry}
        material={materials.mat22}
      />
      <mesh
        
        
        geometry={nodes.mesh918087620.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh918087620_1.geometry}
        material={materials.mat16}
      />
      <mesh
        
        
        geometry={nodes.mesh918087620_2.geometry}
        material={materials.mat22}
      />
      <mesh
        
        
        geometry={nodes.mesh918087620_3.geometry}
        material={materials.mat23}
      />
      <mesh
        
        
        geometry={nodes.mesh700178591.geometry}
        material={materials.mat17}
      />
      <mesh
        
        
        geometry={nodes.mesh700178591_1.geometry}
        material={materials.mat21}
      />
      <mesh
        
        
        geometry={nodes.mesh831255012.geometry}
        material={materials.mat15}
      />
      <mesh
        
        
        geometry={nodes.mesh831255012_1.geometry}
        material={materials.mat17}
      />
    </a.group>
  );
}

export default Vancouver;
